import Foundation
import SwiftUI
import ProxymanCloneKit

struct ComposerWorkspace: View {
    let prefill: ComposerPrefill?
    let prefillToken: UUID
    let onExecuted: (CapturedTransaction) -> Void

    @State private var scheme = "https"
    @State private var host = ""
    @State private var portText = ""
    @State private var method = "GET"
    @State private var target = "/"
    @State private var headers: [EditableComposerHeader] = []
    @State private var includeBody = false
    @State private var requestBody = ""
    @State private var notice: String?
    @State private var statusText = "Ready"
    @State private var isExecuting = false

    private let commonMethods = ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"]

    var body: some View {
        VStack(spacing: 0) {
            HStack(spacing: 10) {
                Text("Composer")
                    .font(.title2.weight(.semibold))
                Spacer()
                Text(statusText)
                    .font(.caption)
                    .foregroundStyle(.secondary)
                    .lineLimit(1)
                Button("New", systemImage: "doc.badge.plus") {
                    reset()
                }
                .disabled(isExecuting)
                Button("Execute", systemImage: "paperplane.fill") {
                    execute()
                }
                .buttonStyle(.borderedProminent)
                .disabled(isExecuting)
            }
            .padding(14)

            Divider()

            ScrollView {
                VStack(alignment: .leading, spacing: 18) {
                    if let notice {
                        Label(notice, systemImage: "exclamationmark.triangle")
                            .font(.callout)
                            .foregroundStyle(.secondary)
                            .padding(10)
                            .frame(maxWidth: .infinity, alignment: .leading)
                            .background(.quaternary.opacity(0.35), in: RoundedRectangle(cornerRadius: 8))
                    }

                    requestLineSection
                    headersSection
                    bodySection

                    Text("Host, Content-Length, Transfer-Encoding, Connection and related framing/hop headers are generated by the engine and cannot be supplied manually.")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
                .padding(18)
                .frame(maxWidth: .infinity, alignment: .leading)
            }
        }
        .task(id: prefillToken) {
            if let prefill {
                apply(prefill)
            }
        }
    }

    private var requestLineSection: some View {
        GroupBox("Request") {
            VStack(alignment: .leading, spacing: 12) {
                HStack(alignment: .bottom, spacing: 10) {
                    VStack(alignment: .leading, spacing: 4) {
                        Text("Scheme").font(.caption).foregroundStyle(.secondary)
                        Picker("Scheme", selection: $scheme) {
                            Text("HTTPS").tag("https")
                            Text("HTTP").tag("http")
                        }
                        .labelsHidden()
                        .pickerStyle(.segmented)
                        .frame(width: 150)
                    }

                    VStack(alignment: .leading, spacing: 4) {
                        Text("Method").font(.caption).foregroundStyle(.secondary)
                        HStack(spacing: 6) {
                            TextField("GET", text: $method)
                                .frame(width: 90)
                            Menu {
                                ForEach(commonMethods, id: \.self) { value in
                                    Button(value) { method = value }
                                }
                            } label: {
                                Image(systemName: "chevron.down")
                            }
                            .menuStyle(.borderlessButton)
                            .frame(width: 24)
                        }
                    }

                    VStack(alignment: .leading, spacing: 4) {
                        Text("Host").font(.caption).foregroundStyle(.secondary)
                        TextField("api.example.com", text: $host)
                            .textFieldStyle(.roundedBorder)
                    }

                    VStack(alignment: .leading, spacing: 4) {
                        Text("Port (optional)").font(.caption).foregroundStyle(.secondary)
                        TextField(scheme == "https" ? "443" : "80", text: $portText)
                            .textFieldStyle(.roundedBorder)
                            .frame(width: 90)
                    }
                }

                VStack(alignment: .leading, spacing: 4) {
                    Text("Target").font(.caption).foregroundStyle(.secondary)
                    TextField("/v1/users?limit=10", text: $target)
                        .font(.system(.body, design: .monospaced))
                        .textFieldStyle(.roundedBorder)
                }
            }
            .padding(6)
        }
    }

    private var headersSection: some View {
        GroupBox("Headers") {
            VStack(alignment: .leading, spacing: 10) {
                if headers.isEmpty {
                    Text("No custom headers")
                        .foregroundStyle(.secondary)
                }

                ForEach($headers) { $header in
                    HStack {
                        TextField("Header name", text: $header.name)
                            .font(.system(.body, design: .monospaced))
                        TextField("Value", text: $header.value)
                            .font(.system(.body, design: .monospaced))
                        Button(role: .destructive) {
                            headers.removeAll { $0.id == header.id }
                        } label: {
                            Image(systemName: "trash")
                        }
                        .buttonStyle(.plain)
                    }
                }

                Button("Add Header", systemImage: "plus") {
                    headers.append(EditableComposerHeader())
                }
            }
            .padding(6)
        }
    }

    private var bodySection: some View {
        GroupBox("Body") {
            VStack(alignment: .leading, spacing: 10) {
                HStack {
                    Toggle("Include request body", isOn: $includeBody)
                    Spacer()
                    Text("\(requestBody.lengthOfBytes(using: .utf8)) bytes UTF-8")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }

                if includeBody {
                    TextEditor(text: $requestBody)
                        .font(.system(.body, design: .monospaced))
                        .frame(minHeight: 180)
                        .padding(6)
                        .background(.quaternary.opacity(0.25), in: RoundedRectangle(cornerRadius: 8))
                } else {
                    Text("No body will be sent and the engine will not add Content-Length.")
                        .foregroundStyle(.secondary)
                }
            }
            .padding(6)
        }
    }

    private func execute() {
        guard !isExecuting else { return }

        let trimmedPort = portText.trimmingCharacters(in: .whitespacesAndNewlines)
        let port: UInt16?
        if trimmedPort.isEmpty {
            port = nil
        } else if let parsed = UInt16(trimmedPort), parsed > 0 {
            port = parsed
        } else {
            statusText = "Port must be between 1 and 65535"
            return
        }

        let customHeaders = headers.compactMap { header -> HeaderField? in
            if header.name.isEmpty && header.value.isEmpty {
                return nil
            }
            return HeaderField(name: header.name, value: header.value)
        }

        let request = ComposedRequest(
            scheme: scheme,
            host: host.trimmingCharacters(in: .whitespacesAndNewlines),
            port: port,
            method: method.trimmingCharacters(in: .whitespacesAndNewlines),
            target: target,
            headers: customHeaders,
            body: includeBody ? requestBody : nil
        )

        isExecuting = true
        statusText = "Executing…"
        Task {
            defer { isExecuting = false }
            do {
                let transaction = try await EngineClient().executeRequest(request)
                statusText = "Captured as transaction \(transaction.id)"
                onExecuted(transaction)
            } catch EngineClientError.engineError(let message) {
                statusText = message
            } catch {
                statusText = "Execution failed: \(error.localizedDescription)"
            }
        }
    }

    private func apply(_ prefill: ComposerPrefill) {
        scheme = prefill.scheme
        host = prefill.host
        portText = prefill.port.map(String.init) ?? ""
        method = prefill.method
        target = prefill.target
        headers = prefill.headers.map { EditableComposerHeader(name: $0.name, value: $0.value) }
        includeBody = prefill.body != nil
        requestBody = prefill.body ?? ""
        notice = prefill.warning
        statusText = "Loaded captured request"
    }

    private func reset() {
        scheme = "https"
        host = ""
        portText = ""
        method = "GET"
        target = "/"
        headers = []
        includeBody = false
        requestBody = ""
        notice = nil
        statusText = "Ready"
    }
}

private struct EditableComposerHeader: Identifiable, Equatable {
    let id: UUID
    var name: String
    var value: String

    init(id: UUID = UUID(), name: String = "", value: String = "") {
        self.id = id
        self.name = name
        self.value = value
    }
}
